### ISSUE TITLE
is this still working?

### ISSUE THREAD

**Issue by ynawahab** [UCF/Online-Theme#40]
hi please advise if this is still working because i have tried the code but my field is empty :(

**Comment by cjg89** [comment]
Hi, can you give us more information about what you're trying to do?  What do you mean specifically by the "field is empty"?

**Comment by ynawahab** [comment]
I have 2 number fields (Profit 1) and (Profit 2) which is working using conditional logic. I wanted to get always the value of the profit in one field so i create (final profit) which is having the merge tag of prfit1 and profit2 so it will always have the value of the chosen profit. But my profit3 is empty

**Comment by cjg89** [comment]
So you're talking about the field-to-field merge tag mapping script?  That code is not written by us--it is just copied and included in this theme.  The original can be found here:  https://gist.github.com/spivurno/7029518.  You might have better luck contacting the original author there directly.

I'd suggest making sure that your profit3 field has the "Allow field to be populated dynamically" checkbox checked, and that you're adding the merge tags to the "Parameter Name" field specifically.  Beyond that, I'd suggest getting in touch with the original author for further troubleshooting.  Best of luck!

**Comment by ynawahab** [comment]
oops sorry! Thank you for your time :)
